require File.expand_path("lib/require_first", File.dirname(__FILE__))
require File.expand_path("lib/auxiliary", File.dirname(__FILE__))
require File.expand_path("lib/core", File.dirname(__FILE__))
require File.expand_path("lib/commands", File.dirname(__FILE__))
require File.expand_path("lib/view_processor", File.dirname(__FILE__))
require File.expand_path("lib/search_hash", File.dirname(__FILE__))
