require File.expand_path("lib/require_first", File.dirname(__FILE__))
require File.expand_path("lib/core", File.dirname(__FILE__))
require File.expand_path("lib/parser", File.dirname(__FILE__))
require File.expand_path("lib/view_processor", File.dirname(__FILE__))
require File.expand_path("lib/option_parser", File.dirname(__FILE__))
