# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secret_server.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "SetMasterCredentialsRequest" do
    map :credentials, :string, :string, 1
  end
  add_message "SecretServerReply" do
    optional :status_code, :int32, 1
    optional :error_msg, :string, 2
    repeated :error_backtrace, :string, 3
  end
  add_message "EncryptRequest" do
    optional :plaintext, :string, 1
  end
  add_message "EncryptReply" do
    optional :status_code, :int32, 1
    optional :error_msg, :string, 2
    repeated :error_backtrace, :string, 3
    optional :encrypted_string, :string, 4
  end
  add_message "DecryptRequest" do
    optional :encrypted_string, :string, 1
  end
  add_message "DecryptReply" do
    optional :status_code, :int32, 1
    optional :error_msg, :string, 2
    repeated :error_backtrace, :string, 3
    optional :plaintext, :string, 4
  end
  add_message "GetValueRequest" do
    optional :key, :string, 1
  end
  add_message "GetValueReply" do
    optional :status_code, :int32, 1
    optional :error_msg, :string, 2
    repeated :error_backtrace, :string, 3
    optional :string_value, :string, 4
  end
end

SetMasterCredentialsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("SetMasterCredentialsRequest").msgclass
SecretServerReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("SecretServerReply").msgclass
EncryptRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("EncryptRequest").msgclass
EncryptReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("EncryptReply").msgclass
DecryptRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("DecryptRequest").msgclass
DecryptReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("DecryptReply").msgclass
GetValueRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetValueRequest").msgclass
GetValueReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("GetValueReply").msgclass
