# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: secret_server.proto for package ''

require 'grpc'
require 'secret_server_pb'

module GrpcSecretServer
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'GrpcSecretServer'

    # Set Master credentials
    rpc :SetMasterCredentials, SetMasterCredentialsRequest, SecretServerReply
    rpc :Encrypt, EncryptRequest, EncryptReply
    rpc :Decrypt, DecryptRequest, DecryptReply
    rpc :GetValue, GetValueRequest, GetValueReply
  end

  Stub = Service.rpc_stub_class
end
