{
  :schema=>:violation,
  :table=>:violation,
  :columns=>{
    :severity=>{:type=>:varchar, :size=>20}, # error || warning || ..
    :message=>{:type=>:json},
    :dependency_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:dependency,
      :on_delete=>:cascade,
      :on_update=>:cascade
    },
    :target_node_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:node,
      :on_delete=>:cascade,
      :on_update=>:cascade
    }
  },
  :many_to_one=>[:datacenter]
}
