FROM getdtk/trusty-puppet
MAINTAINER dduvnjak <dario@atlantbh.com>

RUN mkdir -p /etc/puppet/modules

COPY dtk_modules /etc/puppet/modules

COPY docker/manifests /tmp/manifests

RUN puppet apply --debug /tmp/manifests/stage1.pp

RUN puppet apply --debug /tmp/manifests/stage2.pp

RUN puppet apply --debug /tmp/manifests/stage4.pp

RUN apt-get -y install gettext-base

RUN rm -rf /etc/puppet/modules /tmp/*
