{
  :schema=>:port,
  :table=>:link,
  :columns=>{
    :input_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:port,
      :on_delete=>:cascade,
      :on_update=>:cascade
    },
    :output_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:port,
      :on_delete=>:cascade,
      :on_update=>:cascade
    },
    :assembly_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:component,
      :on_delete=>:set_null,
      :on_update=>:set_null
    }
  },
  :many_to_one=>[:library, :datacenter, :component]
}
