{
  :schema=>:link_def,
  :table=>:instance,
  :columns=>{
    :input_component_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:component,
      :on_delete=>:cascade,
      :on_update=>:cascade
    },
    :output_component_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:component,
      :on_delete=>:cascade,
      :on_update=>:cascade
    },
    :link_def_template_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:link_def_template,
      :on_delete=>:cascade,
      :on_update=>:cascade
    }
  },
  :many_to_one=>[:datacenter]
}

