{
  :schema=>:service,
  :table=>:add_on,
  :columns=>{
    :node_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:node,
      :on_delete=>:cascade,
      :on_update=>:cascade
    },
    :node_group_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:node,
      :on_delete=>:cascade,
      :on_update=>:cascade
    }
  },
  :many_to_one => [:component]
}
