# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtkarbiterservice.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dtkarbiterservice.ProviderMessage" do
    optional :message, :string, 1
    optional :blah, :string, 2
  end
  add_message "dtkarbiterservice.ArbiterMessage" do
    optional :message, :string, 1
  end
end

module Dtkarbiterservice
  ProviderMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("dtkarbiterservice.ProviderMessage").msgclass
  ArbiterMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("dtkarbiterservice.ArbiterMessage").msgclass
end
