#!/usr/bin/env bash

echo "*************************"
echo "post-merge hook triggered"
echo "*************************"

echo "Trying to execute bundler..."
if [[ `gem list | grep bundler` ]]; then
  bundle install
else
 echo "Please install Bundler by running 'gem install bundler'"
 exit 1
fi;

commit_messages=`git log ORIG_HEAD..HEAD`

if [[ `echo ${commit_messages} | grep "db:migrate"` ]]; then
 echo "Commit messages indicate that the db migration should be executed."
 echo "Executing..."
 #./utility/dbrebuild.rb
 #./utility/initialize
fi;
