
{
  :impelements_owner=>true,
  :has_ancestor_fields=>true,
  :field_defs=>{
    :updated_at=>{
        :type=>:json,
    },
    :attribute_value=>{
        :type=>:text,
    },
    :needs_to_be_set=>{
        :type=>:boolean,
    },
    :display_name=>{
        :type=>:text,
        :size=>50
    },
    :read_only=>{
        :type=>:boolean,
    },
    :required=>{
        :type=>:boolean,
    },
  },
  :relationships=>{
  }
}

