{
  :schema=>:node,
  :table=>:binding_relation,
  :columns=>{
    :node_binding_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:node_binding,
      :on_delete=>:set_cascade,
      :on_update=>:set_cascade
    },
    :assembly_template_id=>{
      :type=>:bigint,
      :foreign_key_rel_type=>:component,
      :on_delete=>:set_cascade,
      :on_update=>:set_cascade
    }
  },
  :many_to_one=>[:library]
}

