#
# Chef Client Config File
#
# Dynamically generated by Chef - local modifications will be replaced
#
require 'ohai'
require 'json'

o = Ohai::System.new
o.all_plugins
node_name        o[:ec2][:instance_id]
json_attribs "/etc/chef/client-config.json"
log_level          :info
log_location       STDOUT
ssl_verify_mode    :verify_none
chef_server_url    "http://ec2-184-73-175-145.compute-1.amazonaws.com:4000"

validation_client_name "chef-validator"
validation_key           "/etc/chef/validation.pem"
client_key               "/etc/chef/client.pem"

file_cache_path     "/srv/chef/cache"
pid_file            "/var/run/chef/chef-client.pid"
Mixlib::Log::Formatter.show_time = false



