module XYZ
  class LibraryNodes
    def self.get()
      {"library"=> {"public"=> {"node"=> nodes}}}
    end
   private
     def self.nodes()
       ret = Hash.new
       NodesInfo.each do |k,info|
         ret[k] = node_info(info)
       end
       ret
     end
     NodesInfo = {
       "ami-9bce1ef2-small"=> {
         :ami => "ami-9bce1ef2",
         :display_name =>"CentOS 5.6 small"
         :os_type =>"centos",
         :png => "centos.png",
         :size => "m1.small"
       }
     }
     def self.node_info(info)
        {"os_type"=>info[:os_type],
         "type"=>"image",
         "display_name"=> info[:display_name]
         "external_ref"=>
          {"image_id"=>info[:ami],
           "size"=>info[:size],
           "type"=>"ec2_image"},
         "ui"=>
          {"images"=>
            {"tiny"=>"", "tnail"=>info[:png], "display"=>info[:png]}},
         "attribute"=>
          {"host_addresses_ipv4"=>
            {"required"=>false,
             "read_only"=>true,
             "is_port"=>true,
             "cannot_change"=>false,
             "data_type"=>"json",
             "value_derived"=>[nil],
             "semantic_type_summary"=>"host_address_ipv4",
             "display_name"=>"host_addresses_ipv4",
             "dynamic"=>true,
             "hidden"=>false,
             "semantic_type"=>{":array"=>"host_address_ipv4"}}},
         "node_interface"=>
          {"eth0"=>{"type"=>"ethernet", "display_name"=>"eth0"}},
         "monitoring_item"=>
          {"check_ping"=>
            {"enabled"=>true,
             "description"=>"ping",
             "display_name"=>"check_ping"},
           "check_mem"=>
            {"enabled"=>true,
             "description"=>"Free Memory",
             "display_name"=>"check_mem"},
           "check_local_procs"=>
            {"enabled"=>true,
             "description"=>"Processes",
             "display_name"=>"check_local_procs"},
           "check_all_disks"=>
            {"enabled"=>true,
             "description"=>"Free Space All Disks",
             "display_name"=>"check_all_disks"},
           "check_memory_profiler"=>
            {"enabled"=>true,
             "description"=>"Memory Profiler",
             "display_name"=>"check_memory_profiler"},
           "check_iostat"=>
            {"enabled"=>true,
             "description"=>"Iostat",
             "display_name"=>"check_iostat"},
           "check_ssh"=>
            {"enabled"=>true,
             "description"=>"SSH",
             "display_name"=>"check_ssh"}
         }
       }
     end


       "ami-3cd10e55-micro"=>
        {"os_type"=>"redhat",
         "ds_source_obj_type"=>"image",
         "data_source"=>"user_data",
         "ds_key"=>"[:user_data, \"/library/test/ami-3cd10e55\"]",
         "type"=>"image",
         "attribute"=>
          {"host_addresses_ipv4"=>
            {"required"=>false,
             "read_only"=>true,
             "is_port"=>true,
             "cannot_change"=>false,
             "data_type"=>"json",
             "value_derived"=>[nil],
             "semantic_type_summary"=>"host_address_ipv4",
             "display_name"=>"host_addresses_ipv4",
             "dynamic"=>true,
             "hidden"=>false,
             "semantic_type"=>{":array"=>"host_address_ipv4"}}},
         "node_interface"=>
          {"eth0"=>{"type"=>"ethernet", "display_name"=>"eth0"}},
         "display_name"=>"RH5.7 64 micro",
         "external_ref"=>
          {"image_id"=>"ami-3cd10e55",
           "size"=>"t1.micro",
           "type"=>"ec2_image"},
         "ui"=>
          {"images"=>
            {"tiny"=>"", "tnail"=>"redhat.png", "display"=>"redhat.png"}},
         "monitoring_item"=>
          {"check_ping"=>
            {"enabled"=>true,
             "description"=>"ping",
             "display_name"=>"check_ping"},
           "check_mem"=>
            {"enabled"=>true,
             "description"=>"Free Memory",
             "display_name"=>"check_mem"},
           "check_local_procs"=>
            {"enabled"=>true,
             "description"=>"Processes",
             "display_name"=>"check_local_procs"},
           "check_all_disks"=>
            {"enabled"=>true,
             "description"=>"Free Space All Disks",
             "display_name"=>"check_all_disks"},
           "check_memory_profiler"=>
            {"enabled"=>true,
             "description"=>"Memory Profiler",
             "display_name"=>"check_memory_profiler"},
           "check_iostat"=>
            {"enabled"=>true,
             "description"=>"Iostat",
             "display_name"=>"check_iostat"},
           "check_ssh"=>
            {"enabled"=>true,
             "description"=>"SSH",
             "display_name"=>"check_ssh"}}},
       "ami-3cd10e55-large"=>
        {"os_type"=>"redhat",
         "ds_source_obj_type"=>"image",
         "data_source"=>"user_data",
         "ds_key"=>"[:user_data, \"/library/test/ami-3cd10e55\"]",
         "type"=>"image",
         "attribute"=>
          {"host_addresses_ipv4"=>
            {"required"=>false,
             "read_only"=>true,
             "is_port"=>true,
             "cannot_change"=>false,
             "data_type"=>"json",
             "value_derived"=>[nil],
             "semantic_type_summary"=>"host_address_ipv4",
             "display_name"=>"host_addresses_ipv4",
             "dynamic"=>true,
             "hidden"=>false,
             "semantic_type"=>{":array"=>"host_address_ipv4"}}},
         "node_interface"=>
          {"eth0"=>{"type"=>"ethernet", "display_name"=>"eth0"}},
         "display_name"=>"RH5.7 64 large",
         "external_ref"=>
          {"image_id"=>"ami-3cd10e55",
           "size"=>"m1.large",
           "type"=>"ec2_image"},
         "ui"=>
          {"images"=>
            {"tiny"=>"", "tnail"=>"redhat.png", "display"=>"redhat.png"}},
         "monitoring_item"=>
          {"check_ping"=>
            {"enabled"=>true,
             "description"=>"ping",
             "display_name"=>"check_ping"},
           "check_mem"=>
            {"enabled"=>true,
             "description"=>"Free Memory",
             "display_name"=>"check_mem"},
           "check_local_procs"=>
            {"enabled"=>true,
             "description"=>"Processes",
             "display_name"=>"check_local_procs"},
           "check_all_disks"=>
            {"enabled"=>true,
             "description"=>"Free Space All Disks",
             "display_name"=>"check_all_disks"},
           "check_memory_profiler"=>
            {"enabled"=>true,
             "description"=>"Memory Profiler",
             "display_name"=>"check_memory_profiler"},
           "check_iostat"=>
            {"enabled"=>true,
             "description"=>"Iostat",
             "display_name"=>"check_iostat"},
           "check_ssh"=>
            {"enabled"=>true,
             "description"=>"SSH",
             "display_name"=>"check_ssh"}}},
       "ami-aa37c984"=>
        {"os_type"=>"redhat",
         "ds_source_obj_type"=>"image",
         "data_source"=>"user_data",
         "ds_key"=>"[:user_data, \"/library/test/ami-aa37c984\"]",
         "type"=>"image",
         "attribute"=>
          {"host_addresses_ipv4"=>
            {"required"=>false,
             "read_only"=>true,
             "is_port"=>true,
             "cannot_change"=>false,
             "data_type"=>"json",
             "value_derived"=>[nil],
             "semantic_type_summary"=>"host_address_ipv4",
             "display_name"=>"host_addresses_ipv4",
             "dynamic"=>true,
             "hidden"=>false,
             "semantic_type"=>{":array"=>"host_address_ipv4"}}},
         "node_interface"=>
          {"eth0"=>{"type"=>"ethernet", "display_name"=>"eth0"}},
         "display_name"=>"RHEL 5.5",
         "ds_attributes"=>
          {"name"=>"rnp-chef-09-12-mcollective-1-0-redhat-x86_32",
           "location"=>
            "411986592491/rnp-chef-09-12-mcollective-1-0-redhat-x86_32",
           "product_codes"=>[],
           "root_device_name"=>"/dev/sda1",
           "id"=>"ami-aa37c984",
           "tags"=>{},
           "owner_id"=>"411986592491",
           "block_device_mapping"=>
            [{"snapshotId"=>"snap-f9179794",
              "deviceName"=>"/dev/sda1",
              "deleteOnTermination"=>"true",
              "volumeSize"=>8}],
           "type"=>"machine",
           "kernel_id"=>"aki-3af50453",
           "is_public"=>false,
           "description"=>nil,
           "root_device_type"=>"ebs",
           "flavor"=>{"disk"=>nil},
           "virtualizationType"=>"paravirtual",
           "state"=>"available",
           "architecture"=>"i386"},
         "external_ref"=>{"image_id"=>"ami-aa37c984", "type"=>"ec2_image"},
         "ui"=>
          {"images"=>
            {"tiny"=>"", "tnail"=>"redhat.png", "display"=>"redhat.png"}},
         "monitoring_item"=>
          {"check_ping"=>
            {"enabled"=>true,
             "description"=>"ping",
             "display_name"=>"check_ping"},
           "check_mem"=>
            {"enabled"=>true,
             "description"=>"Free Memory",
             "display_name"=>"check_mem"},
           "check_local_procs"=>
            {"enabled"=>true,
             "description"=>"Processes",
             "display_name"=>"check_local_procs"},
           "check_all_disks"=>
            {"enabled"=>true,
             "description"=>"Free Space All Disks",
             "display_name"=>"check_all_disks"},
           "check_memory_profiler"=>
            {"enabled"=>true,
             "description"=>"Memory Profiler",
             "display_name"=>"check_memory_profiler"},
           "check_iostat"=>
            {"enabled"=>true,
             "description"=>"Iostat",
             "display_name"=>"check_iostat"},
           "check_ssh"=>
            {"enabled"=>true,
             "description"=>"SSH",
             "display_name"=>"check_ssh"}}},
       "ami-e7b1618e-small"=>
        {"os_type"=>"ubuntu",
         "ds_source_obj_type"=>"image",
         "data_source"=>"user_data",
         "ds_key"=>"[:user_data, \"/library/test/ami-e7b1618e\"]",
         "type"=>"image",
         "attribute"=>
          {"host_addresses_ipv4"=>
            {"required"=>false,
             "read_only"=>true,
             "is_port"=>true,
             "cannot_change"=>false,
             "data_type"=>"json",
             "value_derived"=>[nil],
             "semantic_type_summary"=>"host_address_ipv4",
             "display_name"=>"host_addresses_ipv4",
             "dynamic"=>true,
             "hidden"=>false,
             "semantic_type"=>{":array"=>"host_address_ipv4"}}},
         "node_interface"=>
          {"eth0"=>{"type"=>"ethernet", "display_name"=>"eth0"}},
         "display_name"=>"Natty small",
         "external_ref"=>
          {"image_id"=>"ami-e7b1618e",
           "size"=>"m1.small",
           "type"=>"ec2_image"},
         "ui"=>
          {"images"=>
            {"tiny"=>"", "tnail"=>"ubuntu.png", "display"=>"ubuntu.png"}},
         "monitoring_item"=>
          {"check_ping"=>
            {"enabled"=>true,
             "description"=>"ping",
             "display_name"=>"check_ping"},
           "check_mem"=>
            {"enabled"=>true,
             "description"=>"Free Memory",
             "display_name"=>"check_mem"},
           "check_local_procs"=>
            {"enabled"=>true,
             "description"=>"Processes",
             "display_name"=>"check_local_procs"},
           "check_all_disks"=>
            {"enabled"=>true,
             "description"=>"Free Space All Disks",
             "display_name"=>"check_all_disks"},
           "check_memory_profiler"=>
            {"enabled"=>true,
             "description"=>"Memory Profiler",
             "display_name"=>"check_memory_profiler"},
           "check_iostat"=>
            {"enabled"=>true,
             "description"=>"Iostat",
             "display_name"=>"check_iostat"},
           "check_ssh"=>
            {"enabled"=>true,
             "description"=>"SSH",
             "display_name"=>"check_ssh"}}},
       "ami-9bce1ef2-micro"=>
        {"os_type"=>"centos",
         "ds_source_obj_type"=>"image",
         "data_source"=>"user_data",
         "ds_key"=>"[:user_data, \"/library/test/ami-9bce1ef2\"]",
         "type"=>"image",
         "attribute"=>
          {"host_addresses_ipv4"=>
            {"required"=>false,
             "read_only"=>true,
             "is_port"=>true,
             "cannot_change"=>false,
             "data_type"=>"json",
             "value_derived"=>[nil],
             "semantic_type_summary"=>"host_address_ipv4",
             "display_name"=>"host_addresses_ipv4",
             "dynamic"=>true,
             "hidden"=>false,
             "semantic_type"=>{":array"=>"host_address_ipv4"}}},
         "node_interface"=>
          {"eth0"=>{"type"=>"ethernet", "display_name"=>"eth0"}},
         "display_name"=>"CentOS 5.6 micro",
         "ds_attributes"=>
          {"name"=>"rnp-chef-09-12-mcollective-1-0-centos-x86_32",
           "location"=>
            "411986592491/rnp-chef-09-12-mcollective-1-0-centos-lucid-x86_32",
           "product_codes"=>[],
           "root_device_name"=>"/dev/sda1",
           "id"=>"ami-9bce1ef2",
           "tags"=>{},
           "owner_id"=>"411986592491",
           "block_device_mapping"=>
            [{"snapshotId"=>"snap-f9179794",
              "deviceName"=>"/dev/sda1",
              "deleteOnTermination"=>"true",
              "volumeSize"=>8}],
           "type"=>"machine",
           "kernel_id"=>"aki-3af50453",
           "is_public"=>false,
           "description"=>nil,
           "root_device_type"=>"ebs",
           "flavor"=>{"disk"=>nil},
           "virtualizationType"=>"paravirtual",
           "state"=>"available",
           "architecture"=>"i386"},
         "external_ref"=>
          {"image_id"=>"ami-9bce1ef2",
           "size"=>"t1.micro",
           "type"=>"ec2_image"},
         "ui"=>
          {"images"=>
            {"tiny"=>"", "tnail"=>"centos.png", "display"=>"centos.png"}},
         "monitoring_item"=>
          {"check_ping"=>
            {"enabled"=>true,
             "description"=>"ping",
             "display_name"=>"check_ping"},
           "check_mem"=>
            {"enabled"=>true,
             "description"=>"Free Memory",
             "display_name"=>"check_mem"},
           "check_local_procs"=>
            {"enabled"=>true,
             "description"=>"Processes",
             "display_name"=>"check_local_procs"},
           "check_all_disks"=>
            {"enabled"=>true,
             "description"=>"Free Space All Disks",
             "display_name"=>"check_all_disks"},
           "check_memory_profiler"=>
            {"enabled"=>true,
             "description"=>"Memory Profiler",
             "display_name"=>"check_memory_profiler"},
           "check_iostat"=>
            {"enabled"=>true,
             "description"=>"Iostat",
             "display_name"=>"check_iostat"},
           "check_ssh"=>
            {"enabled"=>true,
             "description"=>"SSH",
             "display_name"=>"check_ssh"}}},
       "ami-e7b1618e-micro"=>
        {"os_type"=>"ubuntu",
         "ds_source_obj_type"=>"image",
         "data_source"=>"user_data",
         "ds_key"=>"[:user_data, \"/library/test/ami-e7b1618e\"]",
         "type"=>"image",
         "attribute"=>
          {"host_addresses_ipv4"=>
            {"required"=>false,
             "read_only"=>true,
             "is_port"=>true,
             "cannot_change"=>false,
             "data_type"=>"json",
             "value_derived"=>[nil],
             "semantic_type_summary"=>"host_address_ipv4",
             "display_name"=>"host_addresses_ipv4",
             "dynamic"=>true,
             "hidden"=>false,
             "semantic_type"=>{":array"=>"host_address_ipv4"}}},
         "node_interface"=>
          {"eth0"=>{"type"=>"ethernet", "display_name"=>"eth0"}},
         "display_name"=>"Natty micro",
         "external_ref"=>
          {"image_id"=>"ami-e7b1618e",
           "size"=>"t1.micro",
           "type"=>"ec2_image"},
         "ui"=>
          {"images"=>
            {"tiny"=>"", "tnail"=>"ubuntu.png", "display"=>"ubuntu.png"}},
         "monitoring_item"=>
          {"check_ping"=>
            {"enabled"=>true,
             "description"=>"ping",
             "display_name"=>"check_ping"},
           "check_mem"=>
            {"enabled"=>true,
             "description"=>"Free Memory",
             "display_name"=>"check_mem"},
           "check_local_procs"=>
            {"enabled"=>true,
             "description"=>"Processes",
             "display_name"=>"check_local_procs"},
           "check_all_disks"=>
            {"enabled"=>true,
             "description"=>"Free Space All Disks",
             "display_name"=>"check_all_disks"},
           "check_memory_profiler"=>
            {"enabled"=>true,
             "description"=>"Memory Profiler",
             "display_name"=>"check_memory_profiler"},
           "check_iostat"=>
            {"enabled"=>true,
             "description"=>"Iostat",
             "display_name"=>"check_iostat"},
           "check_ssh"=>
            {"enabled"=>true,
             "description"=>"SSH",
             "display_name"=>"check_ssh"}}}},
     "display_name"=>"public"}}}
